### ISSUE TITLE
Comment for /b/uncamelcase/: The first...

### ISSUE THREAD

**Issue by towerofnix** [kyleplo/kyleplo.github.io#2]
The first "M" in the example is replaced with " m", which makes there be a space before the output. Better to replace it with a space iff the character before it is not already a space?

**Comment by kyleplo** [comment]
Yes, I know that. This was a quick project to make, it is fixable.

**Comment by kyleplo** [comment]
Also, you wouldn't capitalize the first letter, so
```javascript
unCamelCasify("mrBlueHasABlueHouseAndABlueCar");
```
returns
```javascript
"mr blue has a blue house and a blue car"
```
